services:
  - type: web
    name: drms-backend
    env: node
    rootDir: drms-backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20

staticSites:
  - name: drms-frontend
    rootDir: drms-frontend
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://drms-2-v3oy.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
